name: Deploy - EC2
on:
  push:
    branches:
      - main
jobs :
  deploy :
    name: deploy to ec2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      env :
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER_NAME  }}
    - name: Deploy to Server  
      run: |
       ssh -o StrictHostKeyChecking=no -i private_key ubuntu@ec2-13-235-75-86.ap-south-1.compute.amazonaws.com 
       hostname
    

